/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubespbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class nilpkn extends javax.swing.JFrame {

    /**
     * Creates new form nilpkn
     */
    public nilpkn() {
        initComponents();
        load_table();
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("1");
        model.addColumn("2");
        model.addColumn("3");
        model.addColumn("4");
        model.addColumn("5");
        model.addColumn("6");
        model.addColumn("7");
        model.addColumn("8");
        model.addColumn("9");
        model.addColumn("10");
        model.addColumn("11");
        model.addColumn("12");
        model.addColumn("13");
        model.addColumn("14");
        
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from nilaipkn";
            java.sql.Connection conn=(Connection)connection.tryConnect();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13),res.getString(14)});
            }
            tnilpkn.setModel(model);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nnama = new javax.swing.JTextField();
        nnim = new javax.swing.JTextField();
        ntempat = new javax.swing.JTextField();
        nsopan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ndk = new javax.swing.JTextField();
        ntj = new javax.swing.JTextField();
        ndp = new javax.swing.JTextField();
        nked = new javax.swing.JTextField();
        nkgaul = new javax.swing.JTextField();
        npeng = new javax.swing.JTextField();
        nkemun = new javax.swing.JTextField();
        nkbic = new javax.swing.JTextField();
        nket = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nwaktu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tnilpkn = new javax.swing.JTable();
        tbrefresh = new javax.swing.JToggleButton();
        tbsimpan = new javax.swing.JToggleButton();
        tbedit = new javax.swing.JToggleButton();
        tbhapus = new javax.swing.JToggleButton();
        tbkeluar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NILAI PKN");

        jLabel2.setText("2.NIM");

        jLabel3.setText("1.NAMA");

        jLabel4.setText("3.TEMPAT");

        jLabel5.setText("5.SOPAN SANTUN");

        jLabel6.setText("6.DISIPLIN KEHADIRAN");

        jLabel7.setText("7.DISIPLIN DALAM PEKERJAAN");

        jLabel8.setText("4.Waktu");

        jLabel9.setText("8.KEDUNGGUHAN KERJA PRAKTEK");

        jLabel10.setText("10.KEMAUAN UNTUK");

        jLabel11.setText("9.TANGGUNG JAWAB");

        jLabel12.setText("12.KETERAMPILAN");

        jLabel13.setText("11.PENGETAHUAN TENTANG ILMU");

        jLabel14.setText("14.KEMAUAN BERGAUL");

        jLabel15.setText("13.KAMAUAN BERBICARA");

        tnilpkn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"
            }
        ));
        tnilpkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnilpknMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tnilpkn);

        tbrefresh.setText("refresh data");
        tbrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrefreshActionPerformed(evt);
            }
        });

        tbsimpan.setText("simpan");
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });

        tbedit.setText("edit");
        tbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeditActionPerformed(evt);
            }
        });

        tbhapus.setText("hapus");
        tbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhapusActionPerformed(evt);
            }
        });

        tbkeluar.setText("keluar");
        tbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nsopan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ntj, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nkemun, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nked, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ndp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ntempat, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                                .addComponent(nnim, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                                .addComponent(nnama, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                                .addComponent(ndk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nwaktu)))))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(tbrefresh)
                                        .addGap(100, 100, 100)
                                        .addComponent(tbsimpan)
                                        .addGap(102, 102, 102)
                                        .addComponent(tbedit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tbhapus)))
                                .addGap(114, 114, 114)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nket, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npeng, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nkbic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nkgaul, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbkeluar))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nsopan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(npeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(ndk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ndp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nkbic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel9)
                        .addComponent(nked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nkgaul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ntj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(nkemun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbrefresh)
                    .addComponent(tbsimpan)
                    .addComponent(tbedit)
                    .addComponent(tbhapus)
                    .addComponent(tbkeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(714, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        // TODO add your handling code here:
        
        String Nama = nnama.getText().trim();
        String NIM = nnim.getText().trim();
        String Tempat = ntempat.getText().trim();
        String waktu = nwaktu.getText().trim();
        String sopansantun = nsopan.getText().trim();
        String disiplinkehadiran = ndk.getText().trim();
        String disiplinpekerjaan = ndp.getText().trim();     
        String kdmkp = nked.getText().trim();
        String tgjawab = ntj.getText().trim();
        String kumtk = nkemun.getText().trim();
        String ptikp = npeng.getText().trim();
        String ketram = nket.getText().trim();
        String kember = nkbic.getText().trim();
        String kemgaul = nkgaul.getText().trim();

        if (Nama.equals("")){
    JOptionPane.showMessageDialog(null, "nama tidak boleh kosong");
 }else if(NIM.equals("")|| Tempat.equals("")|| waktu.equals("")|| sopansantun.equals("")|| disiplinkehadiran.equals("")|| disiplinpekerjaan.equals("")|| kdmkp.equals("")|| tgjawab.equals("")|| kumtk.equals("")|| ptikp.equals("")|| ketram.equals("")|| kember.equals("")|| kemgaul.equals("")) {
     JOptionPane.showMessageDialog(null, "data tidak boleh kosong");
     
 }else{
     try{
         Connection c = connection.tryConnect();
                String sql = "INSERT INTO nilaipkn VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, Nama);
                p.setString(2, NIM);
                p.setString(3, Tempat);
                 p.setString(4, waktu);
                  p.setString(5, sopansantun );
                p.setString(6, disiplinkehadiran);
                p.setString(7, disiplinpekerjaan);
                p.setString(8, kdmkp);
                 p.setString(9, tgjawab);
                  p.setString(10, kumtk);
                  p.setString(11, ptikp);
                p.setString(12, ketram);
                p.setString(13, kember);
                 p.setString(14, kemgaul);
              
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI INPUT");
                
            }catch(SQLException e){
                System.out.println("Error");
                
            }
        }
        
        
        
        
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkeluarActionPerformed
        // TODO add your handling code here:
        new menuadmin().show();
        this.dispose();
    }//GEN-LAST:event_tbkeluarActionPerformed

    private void tnilpknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnilpknMouseClicked
        // TODO add your handling code here:
        int baris = tnilpkn.rowAtPoint(evt.getPoint());
        String ids = tnilpkn.getValueAt(baris, 0).toString();
        nnama.setText(ids);
        String nama = tnilpkn.getValueAt(baris, 1).toString();
        nnim.setText(nama);
        String proposal = tnilpkn.getValueAt(baris, 2).toString();
        ntempat.setText(proposal);
        String status = tnilpkn.getValueAt(baris, 3).toString();
        nwaktu.setText(status);
        String pkn = tnilpkn.getValueAt(baris, 4).toString();
        nsopan.setText(pkn);
        String ta = tnilpkn.getValueAt(baris, 5).toString();
        ndk.setText(ta);
        String dp = tnilpkn.getValueAt(baris, 6).toString();
        ndp.setText(dp);
        String tb = tnilpkn.getValueAt(baris, 7).toString();
        nked.setText(tb);
        String tc = tnilpkn.getValueAt(baris, 8).toString();
        ntj.setText(tc);
        String td = tnilpkn.getValueAt(baris, 9).toString();
        nkemun.setText(td);
        String te = tnilpkn.getValueAt(baris, 10).toString();
        npeng.setText(te);
        String tf = tnilpkn.getValueAt(baris, 11).toString();
        nket.setText(tf);
        String th = tnilpkn.getValueAt(baris, 12).toString();
        nkbic.setText(th);
        String tg = tnilpkn.getValueAt(baris, 13).toString();
        nkgaul.setText(tg);
        
    }//GEN-LAST:event_tnilpknMouseClicked

    private void tbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeditActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE nilaipkn SET Nama = '"+nnama.getText()+"', NIM = '"+nnim.getText()+"', tempat = '"+ntempat.getText()+"',waktu = '"+nwaktu.getText()+"',sopansantun = '"+nsopan.getText()+"',disiplinkehadiran = '"+ndk.getText()+"',disiplinpekerjaan = '"+ndp.getText()+"',kdmkp = '"+nked.getText()+"',tgjawab = '"+ntj.getText()+"',kumtk = '"+nkemun.getText()+"',ptikp = '"+npeng.getText()+"',ketram = '"+nket.getText()+"',kember = '"+nkbic.getText()+"',kemgaul = '"+nkgaul.getText()+"'";
           
            java.sql.Connection conn=(Connection)connection.tryConnect();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_tbeditActionPerformed

    private void tbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhapusActionPerformed
        // TODO add your handling code here:
        Connection conn = connection.tryConnect();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data tersebut?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == 0) {
            
            try {
                java.sql.PreparedStatement stmt = conn.prepareStatement("delete from nilaipkn where Nama ='" + nnama.getText() + "'");
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                
                nnama.setText("");
                nnim.setText("");
                ntempat.setText("");
                nwaktu.setText("");
                nsopan.setText("");
                ndk.setText("");
                ndp.setText("");
                nked.setText("");
                ntj.setText("");
                nkemun.setText("");
                npeng.setText("");
                nket.setText("");
                nkbic.setText("");
                nkgaul.setText("");
                
                
                nnama.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Data gagal di hapus", "Pesan", JOptionPane.ERROR_MESSAGE);
        
    }
    }//GEN-LAST:event_tbhapusActionPerformed

    private void tbrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tnilpkn.getModel();
        model.setRowCount(0);
        load_table();
    }//GEN-LAST:event_tbrefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilpkn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilpkn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilpkn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilpkn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilpkn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ndk;
    private javax.swing.JTextField ndp;
    private javax.swing.JTextField nkbic;
    private javax.swing.JTextField nked;
    private javax.swing.JTextField nkemun;
    private javax.swing.JTextField nket;
    private javax.swing.JTextField nkgaul;
    private javax.swing.JTextField nnama;
    private javax.swing.JTextField nnim;
    private javax.swing.JTextField npeng;
    private javax.swing.JTextField nsopan;
    private javax.swing.JTextField ntempat;
    private javax.swing.JTextField ntj;
    private javax.swing.JTextField nwaktu;
    private javax.swing.JToggleButton tbedit;
    private javax.swing.JToggleButton tbhapus;
    private javax.swing.JToggleButton tbkeluar;
    private javax.swing.JToggleButton tbrefresh;
    private javax.swing.JToggleButton tbsimpan;
    private javax.swing.JTable tnilpkn;
    // End of variables declaration//GEN-END:variables
}
